export const BIRTHDAY_LOADING = 'BIRTHDAY_LOADING';
export const BIRTHDAY_FAILED = 'BIRTHDAY_FAILED';
export const ADD_BIRTHDAY = 'ADD_BIRTHDAY';

export const STUDENT_DETAILS_LOADING = 'STUDENT_DETAILS_LOADING';
export const STUDENT_DETAILS_FAILED = 'STUDENT_DETAILS_FAILED';
export const ADD_STUDENT_DETAILS = 'ADD_STUDENT_DETAILS';

export const EVENTS_LOADING = 'EVENTS_LOADING';
export const EVENTS_FAILED = 'EVENTS_FAILED';
export const ADD_EVENTS = 'ADD_EVENTS';

export const WALL_CONTENT_LOADING = 'WALL_CONTENT_LOADING';
export const WALL_CONTENT_FAILED = 'WALL_CONTENT_FAILED';
export const ADD_WALL_CONTENT = 'ADD_WALL_CONTENT';

export const CLUBS_LOADING = 'CLUBS_LOADING';
export const CLUBS_FAILED = 'CLUBS_FAILED';
export const ADD_CLUBS = 'ADD_CLUBS';

export const HOUSE_COUNCIL_LOADING = 'HOUSE_COUNCIL_LOADING';
export const HOUSE_COUNCIL_FAILED = 'HOUSE_COUNCIL_FAILED';
export const ADD_HOUSE_COUNCIL = 'ADD_HOUSE_COUNCIL';

export const CERTIFICATES_LOADING = 'CERTIFICATES_LOADING';
export const CERTIFICATES_FAILED = 'CERTIFICATES_FAILED';
export const ADD_CERTIFICATES = 'ADD_CERTIFICATES';
